### ISSUE TITLE
Move pinch-to-drag to new gesture system

### ISSUE THREAD

**Issue by camden-bock** [maine-imre/handwaver#61] opened 2019-01-17 19:48 UTC
Points and tools will continue to use the interaction engine.

Otherwise, we will use our own interactions to move things around.

This stems from the Physx colldiers being limited.

This will also help us in an ECS system.

**Comment by Joey-Haney** [comment] 2019-06-10 20:27
Duplicate of #14

**Closed by Joey-Haney** 2019-06-10 20:27 UTC
Labels: enhancement
