### ISSUE TITLE
Move Stretch to be a gesture in the gesture system.

### ISSUE THREAD

**Issue by camden-bock** [maine-imre/handwaver#60] opened 2019-01-17 18:15 UTC

**Comment by cam3715** [comment] 2019-01-17 18:16
The conditions would be similar to the Double Pinch no grasp, except that it would specifically require grasping.

**Comment by cam3715** [comment] 2019-01-17 18:21
This is currenlty implemented by watching for multihandgrasp

**Comment by cam3715** [comment] 2019-01-17 18:21
This move would help us prepare for an ECS system.

**Comment by cam3715** [comment] 2019-01-17 19:46
Turns out that we need this desperately.

**Comment by Joey-Haney** [comment] 2019-06-10 20:27
Duplicate of #14

**Closed by Joey-Haney** 2019-06-10 20:27 UTC
Labels: enhancement
